### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by voicenter** [socketio/socket.io-sticky#1] opened 2021-03-25 12:20 UTC
internal/per_context/primordials.js:23
  return (thisArg, ...args) => ReflectApply(func, thisArg, args);
                                            ^

TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at internal/per_context/primordials.js:23:32
    at getOrSetAsyncId (internal/async_hooks.js:396:7)
    at Server.connectionListener (_http_server.js:414:5)
    at Server.emit (events.js:315:20)
    at process.<anonymous> (C:\Users\Admin\WebstormProjects\socketIOClusterTest\node_modules\@socket.io\sticky\index.js:102:23)
    at process.emit (events.js:327:22)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

Not sure why...

**Comment by darrachequesne** [comment] 2021-03-25 13:25
Hi, I was not able to reproduce (and the CI for the [test/windows](https://github.com/darrachequesne/socket.io-sticky/tree/test/windows) branch was successful).

- which version of Node.js are you using?
- does it always happen? Or is it only for some requests?
- could you please try with WebSocket only? And HTTP long-polling only?

Thanks!

**Comment by darrachequesne** [comment] 2021-07-01 22:43
I was indeed able to reproduce the issue while load testing my cluster.

According to [this](https://nodejs.org/api/child_process.html#child_process_example_sending_a_socket_object), the `socket` object could be `undefined` when reaching the child process, hence the exception.

> Any 'message' handlers in the subprocess should verify that socket exists, as the connection may have been closed during the time it takes to send the connection to the child.

It should be fixed by https://github.com/socketio/socket.io-sticky/commit/7069fbc5bfbc845556f4a5cb8fd8240a1ef24b0e, included in version [`1.0.1`](https://github.com/socketio/socket.io-sticky/releases/tag/1.0.1).

Thanks!

**Closed as completed by darrachequesne** 2021-07-01 22:43 UTC
